In [3]:
import math
import numpy as np
from scipy import stats

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data. <- Linear Algebra

SciPy is a python library that is useful in solving many mathematical equations and algorithms. It is designed on the top of Numpy library that gives more extension of finding scientific mathematical formulae like Matrix Rank, Inverse, polynomial equations, LU Decomposition, etc. Using its high level functions will significantly reduce the complexity of the code and helps in better analyzing the data. SciPy is an interactive Python session used as a data-processing library that is made to compete with its rivalries such as MATLAB, Octave, R-Lab,etc. It has many user-friendly, efficient and easy-to-use functions that helps to solve problems like numerical integration, interpolation, optimization, linear algebra and statistics.

STATS This module contains a large number of probability distributions as well as a growing library of statistical functions.


In [5]:
from numpy import random 
# uniform random numbers in [0,1]
dataOne = np.random.rand(5,5)
dataOne

array([[0.98665019, 0.85276585, 0.88432904, 0.79321027, 0.49616478],
       [0.45970564, 0.29062256, 0.30077848, 0.5091533 , 0.14933602],
       [0.21247773, 0.84172067, 0.1289289 , 0.6603362 , 0.4442086 ],
       [0.14538278, 0.63920298, 0.70999043, 0.64522057, 0.33881822],
       [0.40218848, 0.62593894, 0.6318676 , 0.79426559, 0.67752046]])

In [12]:
dataOne.min()

0.12892890234665322

In [13]:
dataOne.max()


0.9866501921852119

In [14]:
dataOne.mean()

0.5448313711560681

In [15]:
np.mean(dataOne)

0.5448313711560681

In [16]:
np.sum(dataOne)

13.6207842789017

In [17]:
dataOne[1:3]

array([[0.45970564, 0.29062256, 0.30077848, 0.5091533 , 0.14933602],
       [0.21247773, 0.84172067, 0.1289289 , 0.6603362 , 0.4442086 ]])

In [18]:
np.shape(dataOne)

(5, 5)

In [19]:
np.size(dataOne)

25

Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

ndarray.ndim the number of axes (dimensions) of the array.
ndarray.shapethe dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
ndarray.sizethe total number of elements of the array. This is equal to the product of the elements of shape.
ndarray.dtypean object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
ndarray.itemsizethe size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
ndarray.datathe buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [20]:
print('I Love data Science')

I Love data Science


In [21]:
varOne = 25

varTwo = 25.0

varThree = varOne + varTwo

print(varThree)

50.0


In [22]:
varOne = 25

varTwo = 'Hello'

varThree = varOne + varTwo

print(varThree)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

Numbers that don't have a decimal point are integers and are called "int" in python. You can't add a str and an int. But you can turn a number into a string if you use the str() function.



In [23]:
varOne = 25

varTwo = ' Hello'

varThree = str(varOne) + varTwo

print(varThree)

25 Hello


Define a variable that represents a dictionary with 5 INT elements

Use functions from the math module to perform three different math operations on three of the five elements; you may find it easier to define variables for the elements. Feel free to combine elements as needed. Lastly, print out you results separately.

In [24]:
new_dict = [2,5,8,4,12]
print(new_dict)

[2, 5, 8, 4, 12]


Use functions from the math module to perform three different math operations on three of the five elements; you may find it easier to define variables for the elements. Feel free to combine elements as needed. Lastly, print out you results separately.

In [26]:
np.ceil(new_dict)

array([ 2.,  5.,  8.,  4., 12.])

In [27]:
np.floor(new_dict)

array([ 2.,  5.,  8.,  4., 12.])

* **ceil(x)**	Returns the smallest integer greater than or equal to x.
* **copysign(x, y)**	Returns x with the sign of y
* **fabs(x)**	Returns the absolute value of x
* **factorial(x)**	Returns the factorial of x
* **floor(x)**	Returns the largest integer less than or equal to x
* **fmod(x, y)**	Returns the remainder when x is divided by y
* **frexp(x)**	Returns the mantissa and exponent of x as the pair (m, e)
* **fsum(iterable)**	Returns an accurate floating point sum of values in the iterable
* **isfinite(x)**	Returns True if x is neither an infinity nor a NaN (Not a Number)
* **isinf(x)**	Returns True if x is a positive or negative infinity
* **isnan(x)**	Returns True if x is a NaN
* **ldexp(x, i)**	Returns x * (2**i)
* **modf(x)**	Returns the fractional and integer parts of x
* **trunc(x)**	Returns the truncated integer value of x
* **exp(x)**	Returns e**x
* **expm1(x)**	Returns e**x - 1
* **log(x[, base])**	Returns the logarithm of x to the base (defaults to e)
* **log1p(x)**	Returns the natural logarithm of 1+x
* **log2(x)**	Returns the base-2 logarithm of x
* **log10(x)**	Returns the base-10 logarithm of x
* **pow(x, y)**	Returns x raised to the power y
* **sqrt(x)**	Returns the square root of x
* **acos(x)**	Returns the arc cosine of x
* **asin(x)**	Returns the arc sine of x
* **atan(x)**	Returns the arc tangent of x
* **atan2(y, x)**	Returns atan(y / x)
* **cos(x)**	Returns the cosine of x
* **hypot(x, y)**	Returns the Euclidean norm, sqrt(x*x + y*y)
* **sin(x)**	Returns the sine of x
* **tan(x)**	Returns the tangent of x
* **degrees(x)**	Converts angle x from radians to degrees
* **radians(x)**	Converts angle x from degrees to radians
* **acosh(x)**	Returns the inverse hyperbolic cosine of x
* **asinh(x)**	Returns the inverse hyperbolic sine of x
* **atanh(x)**	Returns the inverse hyperbolic tangent of x
* **cosh(x)**	Returns the hyperbolic cosine of x
* **sinh(x)**	Returns the hyperbolic cosine of x
* **tanh(x)**	Returns the hyperbolic tangent of x
* **erf(x)**	Returns the error function at x
* **erfc(x)**	Returns the complementary error function at x
* **gamma(x)**	Returns the Gamma function at x
* **lgamma(x)**	Returns the natural logarithm of the absolute value of the Gamma function at x
* **pi**	Mathematical constant, the ratio of circumference of a circle to it's diameter (3.14159...)
* **e**	mathematical constant e (2.71828...)

<h1> More Control Flow Tools <h1/>

In [31]:
x = int(input("Please enter an integer: "))

Please enter an integer: 1


In [32]:
if x < 0:
...     x = 0
...     print('Negative changed to zero')
... elif x == 0:
...     print('Zero')
... elif x == 1:
...     print('Single')
... else:
...     print('More')

Single


In [33]:
 # Measure some strings:
... words = ['cat', 'window', 'defenestrate']
>>> for w in words:
...     print(w, len(w))

cat 3
window 6
defenestrate 12


In [34]:
>>> for i in range(5):
...     print(i)

0
1
2
3
4


In [36]:
for i in range(5, 10):
    print(i)

5
6
7
8
9


In [37]:
for i in range(0, 10, 3):
    print(i)

0
3
6
9


In [38]:
a = ['Mary', 'had', 'a', 'little', 'lamb']
>>> for i in range(len(a)):
...     print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In [39]:
for n in range(2, 10):
...     for x in range(2, n):
...         if n % x == 0:
...             print(n, 'equals', x, '*', n//x)
...             break
...     else:
...         # loop fell through without finding a factor
...         print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3


In [40]:
for num in range(2, 10):
...     if num % 2 == 0:
...         print("Found an even number", num)
...         continue
...     print("Found a number", num)

Found an even number 2
Found a number 3
Found an even number 4
Found a number 5
Found an even number 6
Found a number 7
Found an even number 8
Found a number 9


In [41]:
def fib(n):    # write Fibonacci series up to n
...     """Print a Fibonacci series up to n."""
...     a, b = 0, 1
...     while a < n:
...         print(a, end=' ')
...         a, b = b, a+b
...     print()

In [42]:
fib(3400)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 


In [1]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")


In [2]:
parrot(1000)   

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [3]:
parrot('a million', 'bereft of life', 'jump')   

-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !


In [4]:
parrot('a thousand', state='pushing up the daisies')

-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


In [5]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

In [6]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


In [7]:
 fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
>>> fruits.count('apple')

2

In [8]:
 fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
>>> fruits.count('apple')

2

In [9]:
fruits.sort()
>>> fruits

['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear']

In [10]:
 from math import pi
>>> [str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

In [11]:
 matrix = [
...     [1, 2, 3, 4],
...     [5, 6, 7, 8],
...     [9, 10, 11, 12],
... ]

In [12]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

In [13]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
>>> del a[0]

In [14]:
a

[1, 66.25, 333, 333, 1234.5]

In [15]:
del a[2:4]

In [16]:
a

[1, 66.25, 1234.5]

In [17]:
t = 12345, 54321, 'hello!'

In [18]:
t

(12345, 54321, 'hello!')

In [20]:
u = t, (1, 2, 3, 4, 5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [22]:
x, y, z = t
x

12345

In [23]:
 tel = {'jack': 4098, 'sape': 4139}
>>> tel['guido'] = 4127
>>> tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [24]:
del tel['sape']
>>> tel['irv'] = 4127
>>> tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [25]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [26]:
 knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
     print(k, v)

gallahad the pure
robin the brave


In [27]:
for i, v in enumerate(['tic', 'tac', 'toe']):
     print(i, v)

0 tic
1 tac
2 toe


In [28]:
questions = ['name', 'quest', 'favorite color']
>>> answers = ['lancelot', 'the holy grail', 'blue']
>>> for q, a in zip(questions, answers):
     print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


In [30]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
         filtered_data.append(value)
filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

In [33]:
import pandas as pd
credit = pd.read_csv('default_credit_card_clients.csv', header =0)
credit.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  SeptemberPay  AugustPay  \
0   1      20000    2          2         1   24             2          2   
1   2     120000    2          2         2   26            -1          2   
2   3      90000    2          2         2   34             0          0   
3   4      50000    2          2         1   37             0          0   
4   5      50000    1          2         1   57            -1          0   

   JulyPay  JunePay  ...  JuneBill  MayBill  AprilBill  SeptemberPayment  \
0       -1       -1  ...         0        0          0                 0   
1        0        0  ...      3272     3455       3261                 0   
2        0        0  ...     14331    14948      15549              1518   
3        0        0  ...     28314    28959      29547              2000   
4       -1        0  ...     20940    19146      19131              2000   

   AugustPayment  JulyPayment  JunePayment  MayPayment  AprilPayment  \
0            689            0            0           0             0   
1           1000         1000         1000           0          2000   
2           1500         1000         1000        1000          5000   
3           2019         1200         1100        1069          1000   
4          36681        10000         9000         689           679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 25 columns]