In [3]:
import math
import numpy as np
from scipy import stats

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data. <- Linear Algebra

SciPy is a python library that is useful in solving many mathematical equations and algorithms. It is designed on the top of Numpy library that gives more extension of finding scientific mathematical formulae like Matrix Rank, Inverse, polynomial equations, LU Decomposition, etc. Using its high level functions will significantly reduce the complexity of the code and helps in better analyzing the data. SciPy is an interactive Python session used as a data-processing library that is made to compete with its rivalries such as MATLAB, Octave, R-Lab,etc. It has many user-friendly, efficient and easy-to-use functions that helps to solve problems like numerical integration, interpolation, optimization, linear algebra and statistics.

STATS This module contains a large number of probability distributions as well as a growing library of statistical functions.


In [5]:
from numpy import random 
# uniform random numbers in [0,1]
dataOne = np.random.rand(5,5)
dataOne

array([[0.98665019, 0.85276585, 0.88432904, 0.79321027, 0.49616478],
       [0.45970564, 0.29062256, 0.30077848, 0.5091533 , 0.14933602],
       [0.21247773, 0.84172067, 0.1289289 , 0.6603362 , 0.4442086 ],
       [0.14538278, 0.63920298, 0.70999043, 0.64522057, 0.33881822],
       [0.40218848, 0.62593894, 0.6318676 , 0.79426559, 0.67752046]])

In [12]:
dataOne.min()

0.12892890234665322

In [13]:
dataOne.max()


0.9866501921852119

In [14]:
dataOne.mean()

0.5448313711560681

In [15]:
np.mean(dataOne)

0.5448313711560681

In [16]:
np.sum(dataOne)

13.6207842789017

In [17]:
dataOne[1:3]

array([[0.45970564, 0.29062256, 0.30077848, 0.5091533 , 0.14933602],
       [0.21247773, 0.84172067, 0.1289289 , 0.6603362 , 0.4442086 ]])

In [18]:
np.shape(dataOne)

(5, 5)

In [19]:
np.size(dataOne)

25

Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

ndarray.ndim the number of axes (dimensions) of the array.
ndarray.shapethe dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
ndarray.sizethe total number of elements of the array. This is equal to the product of the elements of shape.
ndarray.dtypean object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
ndarray.itemsizethe size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
ndarray.datathe buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [20]:
print('I Love data Science')

I Love data Science


In [21]:
varOne = 25

varTwo = 25.0

varThree = varOne + varTwo

print(varThree)

50.0


In [22]:
varOne = 25

varTwo = 'Hello'

varThree = varOne + varTwo

print(varThree)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

Numbers that don't have a decimal point are integers and are called "int" in python. You can't add a str and an int. But you can turn a number into a string if you use the str() function.



In [23]:
varOne = 25

varTwo = ' Hello'

varThree = str(varOne) + varTwo

print(varThree)

25 Hello


Define a variable that represents a dictionary with 5 INT elements

Use functions from the math module to perform three different math operations on three of the five elements; you may find it easier to define variables for the elements. Feel free to combine elements as needed. Lastly, print out you results separately.

In [24]:
new_dict = [2,5,8,4,12]
print(new_dict)

[2, 5, 8, 4, 12]


Use functions from the math module to perform three different math operations on three of the five elements; you may find it easier to define variables for the elements. Feel free to combine elements as needed. Lastly, print out you results separately.

In [26]:
np.ceil(new_dict)

array([ 2.,  5.,  8.,  4., 12.])

In [27]:
np.floor(new_dict)

array([ 2.,  5.,  8.,  4., 12.])

* **ceil(x)**	Returns the smallest integer greater than or equal to x.
* **copysign(x, y)**	Returns x with the sign of y
* **fabs(x)**	Returns the absolute value of x
* **factorial(x)**	Returns the factorial of x
* **floor(x)**	Returns the largest integer less than or equal to x
* **fmod(x, y)**	Returns the remainder when x is divided by y
* **frexp(x)**	Returns the mantissa and exponent of x as the pair (m, e)
* **fsum(iterable)**	Returns an accurate floating point sum of values in the iterable
* **isfinite(x)**	Returns True if x is neither an infinity nor a NaN (Not a Number)
* **isinf(x)**	Returns True if x is a positive or negative infinity
* **isnan(x)**	Returns True if x is a NaN
* **ldexp(x, i)**	Returns x * (2**i)
* **modf(x)**	Returns the fractional and integer parts of x
* **trunc(x)**	Returns the truncated integer value of x
* **exp(x)**	Returns e**x
* **expm1(x)**	Returns e**x - 1
* **log(x[, base])**	Returns the logarithm of x to the base (defaults to e)
* **log1p(x)**	Returns the natural logarithm of 1+x
* **log2(x)**	Returns the base-2 logarithm of x
* **log10(x)**	Returns the base-10 logarithm of x
* **pow(x, y)**	Returns x raised to the power y
* **sqrt(x)**	Returns the square root of x
* **acos(x)**	Returns the arc cosine of x
* **asin(x)**	Returns the arc sine of x
* **atan(x)**	Returns the arc tangent of x
* **atan2(y, x)**	Returns atan(y / x)
* **cos(x)**	Returns the cosine of x
* **hypot(x, y)**	Returns the Euclidean norm, sqrt(x*x + y*y)
* **sin(x)**	Returns the sine of x
* **tan(x)**	Returns the tangent of x
* **degrees(x)**	Converts angle x from radians to degrees
* **radians(x)**	Converts angle x from degrees to radians
* **acosh(x)**	Returns the inverse hyperbolic cosine of x
* **asinh(x)**	Returns the inverse hyperbolic sine of x
* **atanh(x)**	Returns the inverse hyperbolic tangent of x
* **cosh(x)**	Returns the hyperbolic cosine of x
* **sinh(x)**	Returns the hyperbolic cosine of x
* **tanh(x)**	Returns the hyperbolic tangent of x
* **erf(x)**	Returns the error function at x
* **erfc(x)**	Returns the complementary error function at x
* **gamma(x)**	Returns the Gamma function at x
* **lgamma(x)**	Returns the natural logarithm of the absolute value of the Gamma function at x
* **pi**	Mathematical constant, the ratio of circumference of a circle to it's diameter (3.14159...)
* **e**	mathematical constant e (2.71828...)